### ISSUE TITLE
Should we change the Milestone themes?

### ISSUE THREAD

**Issue by emanisgrand** [spacegrubs/primus#3]
MIlestones are now starting from M1 🎉 
The theme is still based on jam, jelly, or gelatin based desserts. 
Should we keep the theme the same or change it? 
If changed, what should the themes be now?

Ideas:
- Science based?
- Satuday morning cartoons?
- Music based?

Better to tackle this sooner rather than later, imo.

**Comment by taterntots** [comment]
I say stick with the jams :)
