### ISSUE TITLE
Setup the multiplayer server and framework (PUN 2)

### ISSUE THREAD

**Issue by serelium** [spacegrubs/primus#6]

**Comment by serelium** [comment]
Going to setup the multiplayer framework + server and make a quick prototype to get everyone connected in the same room/scene.

**Comment by emanisgrand** [comment]
![](https://media.giphy.com/media/lSE2JWAcpggTevqMy6/giphy.gif)

**Comment by serelium** [comment]
Added in:
https://github.com/spacegrubs/primus/commit/4a4a5519ec51e8944b64829d048271a78dbf9223
